### ISSUE TITLE
All commands need to be able to write to defaults and libraries

### ISSUE THREAD

**Issue by alexarice** [agda/agda-pkg#40]
At the moment any command seems to need to be able to write to defaults and libraries, even commands that I would have thought do not need to do this, such as `--help` `list` or `info`. As these files are readonly on my system I can not use these commands as I get the following error:
```
Errno 30] Read-only file system: '/home/alex/.agda/libraries'
Traceback (most recent call last):
  File "/nix/store/gdw9gfkvk9xd3yflaj409xpbnr8drcz3-agda-pkg-0.1.49/bin/.apkg-wrapped", line 6, in <module>
    from apkg.apkg import cli
  File "/nix/store/gdw9gfkvk9xd3yflaj409xpbnr8drcz3-agda-pkg-0.1.49/lib/python3.7/site-packages/apkg/apkg.py", line 13, in <module>
    from .commands              import *
  File "/nix/store/gdw9gfkvk9xd3yflaj409xpbnr8drcz3-agda-pkg-0.1.49/lib/python3.7/site-packages/apkg/commands/__init__.py", line 15, in <module>
    writeAgdaDirFiles()
  File "<string>", line 2, in writeAgdaDirFiles
  File "/nix/store/ajzmrzs9qj4gfmilas81gphig9vc7snq-python3.7-pony-0.7.13/lib/python3.7/site-packages/pony/orm/core.py", line 528, in new_func
    result = func(*args, **kwargs)
  File "/nix/store/gdw9gfkvk9xd3yflaj409xpbnr8drcz3-agda-pkg-0.1.49/lib/python3.7/site-packages/apkg/service/writeAgdaDirFiles.py", line 70, in writeAgdaDirFiles
    AGDA_DEFAULTS_PATH.write_text(default_libraries)
  File "/nix/store/2dcsn57cgaxs92ha5swihrab0g3l2h6g-python3-3.7.7/lib/python3.7/pathlib.py", line 1235, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/nix/store/2dcsn57cgaxs92ha5swihrab0g3l2h6g-python3-3.7.7/lib/python3.7/pathlib.py", line 1203, in open
    opener=self._opener)
  File "/nix/store/2dcsn57cgaxs92ha5swihrab0g3l2h6g-python3-3.7.7/lib/python3.7/pathlib.py", line 1058, in _opener
    return self._accessor.open(self, flags, mode)
OSError: [Errno 30] Read-only file system: '/home/alex/.agda/defaults'
```

I suppose a workaround for now would be if I made a temporary `$AGDA_DIR` ?

**Comment by jonaprieto** [comment]
I agree this must be fixed for the next version, those commands do not need those files.

https://github.com/agda/agda-pkg/blob/4ebf23f233f1ebe5ff45605eb7368b71e6723ee0/apkg/commands/__init__.py#L15

> I suppose a workaround for now would be if I made a temporary `$AGDA_DIR` ?

Yes. 

https://github.com/agda/agda-pkg/blob/4ebf23f233f1ebe5ff45605eb7368b71e6723ee0/apkg/config.py#L23-L27
